workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    scripts:
      - npm install
      - npm run build
      - npx cap add android
      - npx cap sync
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
  
