workflows:
  android-workflow:
    name: Android Build
    instance_type: linux_x2
    scripts:
      - npm install
      - npm run build
      - npx cap add android
      - npx cap sync
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    scripts:
      - npm install
      - npm run build
      - npx cap add ios
      - npx cap sync
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release
    artifacts:
      - build/ios/**/*.ipa
